### ISSUE TITLE
Unable to install plugin; too old

### ISSUE THREAD

**Issue by amh-mw** [admc/sb-sauce-plugin#1]
Firefox 25.0, SeBuilder 2.0.10
- Launch SeBuilder
- Manage Plugins
  FAIL: "Sauce for Selenium Builder 1.1.4 Not Installed; unable to install: Plugin is too old"

**Comment by Zarkonnen** [comment]
I've bumped up the version of the plugin, lemme know if that helps.

**Comment by amh-mw** [comment]
Working, thanks!
