### ISSUE TITLE
Run Test Locally is not enabled

### ISSUE THREAD

**Issue by lakshmi-tilak** [admc/sb-sauce-plugin#4]
HI ,
    I have installed Selenium builder 3.0.5 and import the json script using "Open a script or suite'. 
    Imported file having a input data file to access , For that i have edited the path before importing file.  
   Now under Run option 'Run Test Locally' is not found.

**Comment by Zarkonnen** [comment]
See this issue: https://github.com/SeleniumBuilder/selenium-builder/issues/6
