### ISSUE TITLE
Plugins doesn't work

### ISSUE THREAD

**Issue by Neno79** [admc/sb-sauce-plugin#5]
When i click "Manage Plugins" error popup "Unable to fetch plugins: error".
I'm using Firefox v45 on Windows 8.1.

Please fix, thank you.
![error](https://cloud.githubusercontent.com/assets/18439178/14489254/66b531bc-016c-11e6-8f89-3f2c360fe8af.png)

**Comment by Zarkonnen** [comment]
A fix is underway. NB a better place to report issues with builder is https://github.com/SeleniumBuilder/selenium-builder/issues
