### ISSUE TITLE
Plugin outdated

### ISSUE THREAD

**Issue by simpletome** [admc/sb-sauce-plugin#6]
Sauce for selenium builder unable to install. Might be incompatible with selenium builder itself. Selenium builder just recently been updated to v3.1.2
current sauce for selenium builder version is v3.1.0.3.
Please kindly update. Thanks :)

**Comment by Zarkonnen** [comment]
Done! BTW, the up to date fork of this project is https://github.com/saucelabs/sb-sauce-plugin

**Comment by simpletome** [comment]
Thanks. Awesome work man!
